### ISSUE TITLE
Switching projects while the file selector dialog is open causes a crash

### ISSUE THREAD

**Issue by valadaptive** [mobile-bungalow/tweak_shader_ae_rs#10]
If you:

1. Click the "Select Source" button
2. Leave the file dialog open and create a new project or open a different one
3. Select a file in the dialog

After Effects will crash:
![image](https://github.com/user-attachments/assets/2e410499-eb1d-43a3-a62a-53da88b81c9b)

I tested this on Windows; not sure if it also occurs on macOS.

This could be an issue because it seems that sometimes the dialog appears behind the main AE window, and users could potentially forget that the dialog is open and switch projects.

I ran into this issue with my own plugin when trying to figure out the "right way" to create a file selection dialog in AE. I believe you can get the main window handle with `AEGP_GetMainHWND` and then pass it into `rfd::FileDialog` via `set_parent`, but doing the same thing in Premiere seems to require using their own custom suite (unfortunately not yet implemented in the high-level API in the `after-effects` crate).

**Comment by mobile-bungalow** [comment]
This does not happen on MacOs, which is the only place I test. I'll look into exposing that API the next time I throw a PR at the `after-effects` crate. Thanks for the detailed write up.

**Comment by mobile-bungalow** [comment]
Closed with #11, thanks for the detailed report and solution.

**Comment by mobile-bungalow** [comment]
Closed with #11 , thanks for the detailed report and solution.
