### ISSUE TITLE
Crash when duplicate TweakShader effect

### ISSUE THREAD

**Issue by mixsoupe** [mobile-bungalow/tweak_shader_ae_rs#12]
After effect crash if you duplicate a TweakShader effect present on a layer, no matter which shader is loaded.
On the other hand, if you create a second TweakShader effect and reload the same shader, everything works fine.
I am on Windows, in After Effect 25.0.1

**Comment by mobile-bungalow** [comment]
this is a side effect of #6 , It will require [removing this ill advised macro](https://github.com/mobile-bungalow/tweak_shader_ae_plugin/blob/6b8f6e640835f9c7f2256a3cb874e6bfaea6856f/src/types.rs#L141). I don't have the time to work on this right now, but I might in a few weeks. thanks for reporting this.

**Comment by mobile-bungalow** [comment]
[fix deployed here](https://github.com/mobile-bungalow/tweak_shader_ae_plugin/pull/14), I have tested the build on macos, it uses a little bit more memory and is slower to start up rendering but it fixes the crash.
