### ISSUE TITLE
16 bpc Issue

### ISSUE THREAD

**Issue by mixsoupe** [mobile-bungalow/tweak_shader_ae_rs#9]
After a quick try to discover this plugin, which seems awesome, it seems that there is a problem when after effect is in 16bits.
No matter the shader, it outputs a transparent alpha.
Everything works well in 8bits or 32bits
My config:
AE 24.6.2
RTX 3060 Drivers 560.94

**Comment by mobile-bungalow** [comment]
Thanks for filing a bug. Please provide the shader that exhibits this behavior, are you on windows or MacOs?

Edit: oh, it's all of them. I'll fix this.

**Comment by mobile-bungalow** [comment]
This should be fixed in the most recent [build](https://github.com/mobile-bungalow/tweak_shader_ae_plugin/actions/runs/11357664962). I tested on MacOs although I cannot test on windows at the moment. I will create a new release when I have confirmed it works there.

**Comment by mixsoupe** [comment]
I tested the build on Windows and it now works in 16bit.
Thanks a lot!
